In [1]:
q1="I just discovered the course, can I still join ?"
q2="I just found out about the program, can I still enroll"

In [2]:
from sentence_transformers import SentenceTransformer

In [3]:
model = SentenceTransformer("all-MiniLM-L6-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [4]:
query_embedding = model.encode(q1)

In [5]:
query_embedding

array([-7.94800185e-03, -9.18932408e-02, -1.14073846e-02,  2.18466409e-02,
        1.11858314e-02, -1.30818216e-02, -7.39962757e-02, -9.87467319e-02,
       -1.05911419e-01, -3.03381458e-02, -2.92174220e-02,  2.33883392e-02,
        7.87485298e-03,  4.15800139e-02,  2.42720451e-02, -3.65723781e-02,
       -5.31095676e-02, -1.94869023e-02, -2.26979572e-02,  8.76777619e-03,
       -1.10785276e-01,  3.97906974e-02, -4.18479890e-02,  2.82960683e-02,
       -1.28302388e-02,  1.72567554e-02,  3.10428329e-02,  9.51102972e-02,
       -1.90717634e-02, -6.23235777e-02, -3.59101035e-02,  6.46180212e-02,
        3.06464713e-02,  2.39972360e-02,  2.06127428e-02,  9.87381488e-03,
        7.63836280e-02, -6.50510639e-02,  4.07932140e-03,  2.34527793e-02,
       -2.49407385e-02, -2.95020398e-02, -1.74879283e-02,  4.62139472e-02,
        2.48923060e-02,  1.08981699e-01, -5.67837507e-02, -6.95324764e-02,
        4.35408251e-03,  2.85131857e-02,  2.75795460e-02, -2.49844026e-02,
       -6.82144938e-03,  

In [6]:
query_embedding.shape

(384,)

In [7]:
qe2 = model.encode(q2)

In [8]:
qe2

array([-1.72461327e-02, -9.24023893e-03, -3.62572307e-03, -6.82149874e-03,
        4.69580330e-02,  3.79793607e-02, -4.21815105e-02, -1.00857113e-02,
       -9.40258503e-02, -2.59940103e-02, -8.45036469e-03,  8.36389884e-02,
        7.49911275e-03, -4.34852242e-02,  1.60788782e-02, -2.72742137e-02,
       -6.24462310e-03, -1.01124346e-02,  1.25456331e-02,  1.80859212e-02,
       -6.50386289e-02,  3.29030640e-02, -1.20977610e-01,  3.66081335e-02,
        8.16317722e-02,  1.69266202e-02,  6.14656787e-03,  6.57961220e-02,
        6.11800700e-03,  2.72710677e-02,  3.52811478e-02,  6.96577206e-02,
        6.83740601e-02, -2.01484258e-03,  4.55028601e-02, -4.03997414e-02,
        4.62867925e-03,  5.29858563e-03, -5.58704510e-02,  4.41499352e-02,
       -3.02829593e-02, -3.13588120e-02, -5.41151762e-02,  7.80768245e-02,
        2.70012114e-02, -2.14240532e-02, -1.23374701e-01, -4.59570158e-03,
        3.88870686e-02,  4.99097928e-02,  9.04886238e-03, -6.26738071e-02,
        5.18102981e-02,  

In [9]:
qe2.shape

(384,)

In [10]:
q1 = 'Can I still join the course after the start date?'
v1 = model.encode(q1)

In [11]:
d  = "You don't need to register. You're accepted. You can also just start learning and submitting homework without registering."
dv = model.encode(d)

In [12]:
v1.dot(dv)

np.float32(0.323324)

In [13]:
q2 = 'How to install Docker on Windows?'
v2 = model.encode(q2)

In [14]:
v2.dot(dv)

np.float32(0.019730432)

In [18]:
import sys
sys.path.append('/app')
from ingest import load_faq_data, build_index

documents = load_faq_data()

In [25]:
# Docuemtns is a dict
documents[10]


{'course': 'data-engineering-zoomcamp',
 'section': 'General Course-Related Questions',
 'question': 'Course: How many hours per week am I expected to spend on this course?',
 'answer': 'It depends on your background and previous experience with modules. It is expected to require about 5 - 15 hours per week.\n\nYou can also calculate it yourself using [this data](https://github.com/DataTalksClub/zoomcamp-analytics/tree/main/data/de-zoomcamp-2023) and then update this answer.',
 'doc_id': '316180784f'}

In [23]:
texts = []
for doc in documents: 
    text=doc['question'] + '' + doc['answer']
    texts.append(text)

In [27]:
texts[10]
len(texts)

1350

In [29]:
from  tqdm.auto import tqdm
batch_size=50
vectors=[]
for i in tqdm(range(0, len(texts), batch_size)):
    batch = texts[i:i + batch_size]
    batch_vectors = model.encode(batch)
    vectors.extend(batch_vectors)

len(vectors)

  0%|          | 0/27 [00:00<?, ?it/s]

1350

In [31]:
vectors[10].shape

(384,)

In [32]:
v1.dot(vectors[10])

np.float32(0.33153278)

In [35]:
scores = []
for i in range(len(vectors)):
    score = v1.dot(vectors[i])
    scores.append(score)
scores

[np.float32(0.48740578),
 np.float32(0.20991933),
 np.float32(0.7629412),
 np.float32(0.44378537),
 np.float32(0.26084),
 np.float32(0.48665166),
 np.float32(0.30061555),
 np.float32(0.56009996),
 np.float32(0.45960492),
 np.float32(0.25628173),
 np.float32(0.33153278),
 np.float32(0.27318528),
 np.float32(0.2769164),
 np.float32(0.34123006),
 np.float32(0.4600717),
 np.float32(0.26240283),
 np.float32(0.3920009),
 np.float32(0.108541705),
 np.float32(0.2756731),
 np.float32(0.16646814),
 np.float32(0.31437927),
 np.float32(0.006685457),
 np.float32(0.1120503),
 np.float32(0.21905686),
 np.float32(0.3400085),
 np.float32(0.23571303),
 np.float32(0.32714847),
 np.float32(0.15088364),
 np.float32(0.1656328),
 np.float32(0.05795122),
 np.float32(0.23541196),
 np.float32(0.113408834),
 np.float32(-0.0030899234),
 np.float32(-0.03754048),
 np.float32(-0.071822226),
 np.float32(-0.0022777244),
 np.float32(-0.00083284266),
 np.float32(-0.049628817),
 np.float32(0.009299926),
 np.float32(-0.01

In [36]:
import numpy as np
X = np.array(vectors)

In [37]:
scores = X.dot(v1)

In [38]:
scores

array([ 0.48740578,  0.20991933,  0.7629412 , ..., -0.08637966,
        0.03759791, -0.02661391], shape=(1350,), dtype=float32)

In [40]:
idx = np.argmax(scores)
idx, scores[idx]

(np.int64(2), np.float32(0.7629412))

In [41]:
documents[2]

{'course': 'data-engineering-zoomcamp',
 'section': 'General Course-Related Questions',
 'question': 'Course: Can I still join the course after the start date?',
 'answer': "Yes, even if you don't register, you're still eligible to submit the homework.\n\nBe aware, however, that there will be deadlines for turning in homeworks and the final projects. So don't leave everything for the last minute.",
 'doc_id': '3f1424af17'}

In [47]:
top5 = np.argsort(scores)[-5:]
top5 = top5[::-1]

In [48]:
scores[top5]

array([0.7629412 , 0.7579371 , 0.7192131 , 0.65363115, 0.56009996],
      dtype=float32)

In [50]:
for idx in top5: 
    print(scores[idx])
    print(documents[idx])
    print()

0.7629412
{'course': 'data-engineering-zoomcamp', 'section': 'General Course-Related Questions', 'question': 'Course: Can I still join the course after the start date?', 'answer': "Yes, even if you don't register, you're still eligible to submit the homework.\n\nBe aware, however, that there will be deadlines for turning in homeworks and the final projects. So don't leave everything for the last minute.", 'doc_id': '3f1424af17'}

0.7579371
{'course': 'mlops-zoomcamp', 'section': 'General Course-Related Questions', 'question': 'Course - Can I still join the course after the start date?', 'answer': "Yes, even if you don't register, you're still eligible to submit the homeworks as long as the form is still open and accepting submissions.\n\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything to the last minute.", 'doc_id': '2d8b16c2a0'}

0.7192131
{'course': 'machine-learning-zoomcamp', 'section': 'General Course-Related Questions',

### Vector Search with minsearch


In [55]:
from minsearch import VectorSearch

vindex = VectorSearch(keyword_fields=['course'])
vindex.fit(X, documents)

In [59]:
vindex.search(v1, num_results=5, filter_dict={'course':'llm-zoomcamp'})

[{'course': 'llm-zoomcamp',
  'section': 'General Course-Related Questions',
  'question': 'I just discovered the course. Can I still join?',
  'answer': 'Yes, but if you want to receive a certificate, you need to submit your project while we’re still accepting submissions.',
  'doc_id': '74eb249bbf'},
 {'course': 'llm-zoomcamp',
  'section': 'General Course-Related Questions',
  'question': 'When will the course be offered next?',
  'answer': 'Summer 2027.',
  'doc_id': 'bd31146b0e'},
 {'course': 'llm-zoomcamp',
  'section': 'General Course-Related Questions',
  'question': 'Certificate: Can I follow the course in a self-paced mode and get a certificate?',
  'answer': 'No, you can only get a certificate if you finish the course with a "live" cohort.\n\nWe don\'t award certificates for the self-paced mode. The reason is you need to peer-review 3 capstone(s) after submitting your project.\n\nYou can only peer-review projects at the time the course is running; after the form is closed an